### ISSUE TITLE
关于翻译 - 任务认领

### ISSUE THREAD

**Issue by keifergu** [GraphQL-China/graphql-china.github.io#17]
### 翻译
- 翻译前，请在[此处查看任务情况](https://github.com/GraphQL-China/graphql.github.io/projects/1)。
- 进入对应 issue，回复进行认领。
- 认领示例： #16 
- 认领格式 ：此章节由我翻译，翻译时间为 2017.07.01-2017.07.14。
- 如果本人认领，然后发现没有时间翻译，可以取消认领。
- 取消认领格式：此章节我暂时没有时间翻译，请其他同学协助代为翻译，谢谢！
- 翻译完成，到领取的 issue 中回复：此章节我已翻译完成。官方维护人员收到留言消息提示后，关闭对应 issue。

**Comment by linonetwo** [comment]
要不要用右边的那个 Assignees ？

**Comment by jonirrings** [comment]
用~~挺好用，不过那是asign给repo admin/member来处理这个issue的意思吧？

**Comment by linonetwo** [comment]
这样啊，不过翻译任务很少有除了  admin/member 以外的第三方来提 issue，我们在这个 repo 里可以重新定义一下它的意思，就是接任务的意思。

用了它有一个好处就是 issue 列表会显示头像……

**Comment by jonirrings** [comment]
(๑•̀ㅂ•́)و✧那就这么办了

**Comment by ydfzgyj** [comment]
assignee 只有 issue 的发布者和项目 owner 可以改吧，得有人负责盯着才行……

**Comment by linonetwo** [comment]
那我路过 issue 的时候顺手帮忙加了，没加也无所谓。
